knownNM_Names = {
    "Abyssdiver", 
    "Arke", 
    "Ayapec", 
    "Azrael", 
    "Azure-toothed Clawberry", 
    "Bakunawa", 
    "Beist", 
    "Borealis Shadow", 
    "Bounding Belinda", 
    "Cactrot Veloz", 
    "Camahueto", 
    "Carousing Celine", 
    "Centurio XX-I", 
    "Coca", 
    "Douma Weapon", 
    "Emperor Arthro", 
    "Garbage Gel", 
    "Glazemane", 
    "Grand Grenade", 
    "Hidhaegg", 
    "Hugemaw Harold", 
    "Immanibugard", 
    "Intuila", 
    "Ironhorn Baldurno", 
    "Jester Malatrix", 
    "Joyous Green", 
    "Keeper of Heiligtum", 
    "King Uropygid", 
    "Kubool Ja's Mhuufya", 
    "Largantua", 
    "Lumber Jill", 
    "Mephitas", 
    "Muut", 
    "Orcfeltrap", 
    "Prickly Pitriv", 
    "Sarama", 
    "Serpopard Ninlil", 
    "Shedu", 
    "Sleepy Mabel", 
    "Sovereign Behemoth", 
    "Specter Worm", 
    "Strix", 
    "Sybaritic Samantha", 
    "Thu'ban", 
    "Tiyanak", 
    "Tolba", 
    "Tumult Curator", 
    "Valkurm Imperator", 
    "Vedrfolnir", 
    "Vermillion Fishfly", 
    "Vidmapire", 
    "Volatile Cluster", 
    "Voso", 
    "Warblade Beak", 
    "Woodland Mender", 
    "Wyvernhunter Bambrox", 
}

knownNM_Coffers = {
    ["Abyssdiver"] = "Abyssdiver's Coffer", 
    ["Arke"] = "Arke's Coffer", 
    ["Ayapec"] = "Ayapec's Coffer", 
    ["Azrael"] = "Azrael's Coffer", 
    ["Azure-toothed Clawberry"] = "Clawberry's Coffer", 
    ["Bakunawa"] = "Bakunawa's Coffer", 
    ["Beist"] = "Beist's Coffer", 
    ["Borealis Shadow"] = "Borealis Shadow's Coffer", 
    ["Bounding Belinda"] = "Bounding Belinda's Coffer", 
    ["Cactrot Veloz"] = "Cactrot Veloz's Coffer", 
    ["Camahueto"] = "Camahueto's Coffer", 
    ["Carousing Celine"] = "Celine's Coffer", 
    ["Centurio XX-I"] = "Centurio XX-I's Coffer", 
    ["Coca"] = "Coca's Coffer", 
    ["Douma Weapon"] = "Douma Weapon's Coffer", 
    ["Emperor Arthro"] = "Emperor Arthro's Coffer", 
    ["Garbage Gel"] = "Garbage's Coffer", 
    ["Glazemane"] = "Glazemane's Coffer", 
    ["Grand Grenade"] = "G. Grenade's Coffer", 
    ["Hidhaegg"] = "Hidhaegg's Coffer", 
    ["Hugemaw Harold"] = "Hugemaw Harold's Coffer", 
    ["Immanibugard"] = "Immanibugard's Coffer", 
    ["Intuila"] = "Intuila's Coffer", 
    ["Ironhorn Baldurno"] = "Ironhorn Baldurno's Coffer", 
    ["Jester Malatrix"] = "Jester Malatrix's Coffer", 
    ["Joyous Green"] = "Joyous Green's Coffer", 
    ["Keeper of Heiligtum"] = "Heiligtum's Coffer", 
    ["King Uropygid"] = "Uropygid's Coffer", 
    ["Kubool Ja's Mhuufya"] = "Mhuufya's Coffer", 
    ["Largantua"] = "Largantua's Coffer", 
    ["Lumber Jill"] = "Lumber Jill's Coffer", 
    ["Mephitas"] = "Mephitas's Coffer", 
    ["Muut"] = "Muut's Coffer", 
    ["Orcfeltrap"] = "Orcfeltrap's Coffer", 
    ["Prickly Pitriv"] = "Prickly Pitriv's Coffer", 
    ["Sarama"] = "Sarama's Coffer", 
    ["Serpopard Ninlil"] = "Serpopard Ninlil's Coffer", 
    ["Shedu"] = "Shedu's Coffer", 
    ["Sleepy Mabel"] = "Sleepy Mabel's Coffer", 
    ["Sovereign Behemoth"] = "Sovereign Coffer", 
    ["Specter Worm"] = "Specter Worm's Coffer", 
    ["Strix"] = "Strix's Coffer", 
    ["Sybaritic Samantha"] = "Saman. Coffer", 
    ["Thu'ban"] = "Thu'ban's Coffer", 
    ["Tiyanak"] = "Tiyanak's Coffer", 
    ["Tolba"] = "Tolba's Coffer", 
    ["Tumult Curator"] = "Tumult Coffer", 
    ["Valkurm Imperator"] = "Imperator's Coffer", 
    ["Vedrfolnir"] = "Vedrfolnir's Coffer", 
    ["Vermillion Fishfly"] = "Vermillion's Coffer", 
    ["Vidmapire"] = "Vidmapire's coffer", 
    ["Volatile Cluster"] = "Volatile's Coffer", 
    ["Voso"] = "Voso's Coffer", 
    ["Warblade Beak"] = "Warblade Beak's Coffer", 
    ["Woodland Mender"] = "Woodland Mender's Coffer", 
    ["Wyvernhunter Bambrox"] = "Bambrox's Coffer", 
}


knownNM_CoffersID = {
    ["Abyssdiver's Coffer"] = 6319, 
    ["Arke's Coffer"] = 6327, 
    ["Ayapec's Coffer"] = 6363, 
    ["Azrael's Coffer"] = 6365, 
    ["Clawberry's Coffer"] = 6384, 
    ["Bakunawa's Coffer"] = 6383, 
    ["Beist's Coffer"] = 6329, 
    ["Borealis Shadow's Coffer"] = 6366, 
    ["Bounding Belinda's Coffer"] = 6313, 
    ["Cactrot Veloz's Coffer"] = 6331, 
    ["Camahueto's Coffer"] = 6359, 
    ["Celine's Coffer"] = 6484, 
    ["Centurio XX-I's Coffer"] = 6390, 
    ["Coca's Coffer"] = 6362, 
    ["Douma Weapon's Coffer"] = 6352, 
    ["Emperor Arthro's Coffer"] = 6321, 
    ["Garbage's Coffer"] = 6382, 
    ["Glazemane's Coffer"] = 6483, 
    ["G. Grenade's Coffer"] = 6388, 
    ["Hidhaegg's Coffer"] = 6404, 
    ["Hugemaw Harold's Coffer"] = 6312, 
    ["Immanibugard's Coffer"] = 6357, 
    ["Intuila's Coffer"] = 6320, 
    ["Ironhorn Baldurno's Coffer"] = 6315, 
    ["Jester Malatrix's Coffer"] = 6330, 
    ["Joyous Green's Coffer"] = 6324, 
    ["Heiligtum's Coffer"] = 6351, 
    ["Uropygid's Coffer"] = 6353, 
    ["Mhuufya's Coffer"] = 6387, 
    ["Largantua's Coffer"] = 6328, 
    ["Lumber Jill's Coffer"] = 6323, 
    ["Mephitas's Coffer"] = 6361, 
    ["Muut's Coffer"] = 6358, 
    ["Orcfeltrap's Coffer"] = 6322, 
    ["Prickly Pitriv's Coffer"] = 6314, 
    ["Sarama's Coffer"] = 6481, 
    ["Serpopard Ninlil's Coffer"] = 6318, 
    ["Shedu's Coffer"] = 6482, 
    ["Sleepy Mabel's Coffer"] = 6316, 
    ["Sovereign Coffer"] = 6404, 
    ["Specter Worm's Coffer"] = 6364, 
    ["Strix's Coffer"] = 6325, 
    ["Saman. Coffer"] = 6350, 
    ["Thu'ban's Coffer"] = 6480, 
    ["Tiyanak's Coffer"] = 6356, 
    ["Tolba's Coffer"] = 6403, 
    ["Tumult Coffer"] = 6479, 
    ["Imperator's Coffer"] = 6317, 
    ["Vedrfolnir's Coffer"] = 6354, 
    ["Vermillion's Coffer"] = 6385, 
    ["Vidmapire's coffer"] = 6386, 
    ["Volatile's Coffer"] = 6386, 
    ["Voso's Coffer"] = 6360, 
    ["Warblade Beak's Coffer"] = 6326, 
    ["Woodland Mender's Coffer"] = 6332, 
    ["Bambrox's Coffer"] = 6485
}

function table.contains(table, element)
    for _, value in pairs(table) do
        if value == element then
            return true
        end
    end
    return false
end

function trim(s)
    return (s:gsub("^%s*(.-)%s*$", "%1"))
end
